comenta los test

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -21,21 +21,21 @@ jobs:
       - run: npm ci
 
       # 🔎 Paso opcional de validación para evitar builds "vacíos"
-      - name: Validate VITE envs
-        run: |
-          test -n "$VITE_FIREBASE_API_KEY" || (echo "Missing VITE_FIREBASE_API_KEY" && exit 1)
-          test -n "$VITE_FIREBASE_AUTH_DOMAIN" || (echo "Missing VITE_FIREBASE_AUTH_DOMAIN" && exit 1)
-          test -n "$VITE_FIREBASE_PROJECT_ID" || (echo "Missing VITE_FIREBASE_PROJECT_ID" && exit 1)
-          test -n "$VITE_FIREBASE_APP_ID" || (echo "Missing VITE_FIREBASE_APP_ID" && exit 1)
-          test -n "$VITE_FIREBASE_MESSAGING_SENDER_ID" || (echo "Missing VITE_FIREBASE_MESSAGING_SENDER_ID" && exit 1)
-          test -n "$VITE_FIREBASE_STORAGE_BUCKET" || (echo "Missing VITE_FIREBASE_STORAGE_BUCKET" && exit 1)
-        env:
-          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
-          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
-          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
-          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
-          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
-          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
+      #- name: Validate VITE envs
+      #  run: |
+      #    test -n "$VITE_FIREBASE_API_KEY" || (echo "Missing VITE_FIREBASE_API_KEY" && exit 1)
+      #    test -n "$VITE_FIREBASE_AUTH_DOMAIN" || (echo "Missing VITE_FIREBASE_AUTH_DOMAIN" && exit 1)
+      #    test -n "$VITE_FIREBASE_PROJECT_ID" || (echo "Missing VITE_FIREBASE_PROJECT_ID" && exit 1)
+      #    test -n "$VITE_FIREBASE_APP_ID" || (echo "Missing VITE_FIREBASE_APP_ID" && exit 1)
+      #    test -n "$VITE_FIREBASE_MESSAGING_SENDER_ID" || (echo "Missing VITE_FIREBASE_MESSAGING_SENDER_ID" && exit 1)
+      #    test -n "$VITE_FIREBASE_STORAGE_BUCKET" || (echo "Missing VITE_FIREBASE_STORAGE_BUCKET" && exit 1)
+      #  env:
+      #    VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
+      #    VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
+      #    VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
+      #    VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
+      #    VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
+      #    VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
       - name: Build
         run: npm run build
         env:
